### ISSUE TITLE
CV2 not listed on pip

### ISSUE THREAD

**Issue by boysugi20** [Qengineering/RPi-image#10]
hello, can someone please help

when I use this RPI-image on my Raspberry Pi 4B 8GB, I could import cv2 on python just fine
but when I wanted to install other packages with opencv-python as dependencies, the installation would fail when it tried to install opencv-python

tried 'pip3 show opencv-python' and 'pip3 list', no opencv-python package detected

Any kind of help would be greatly appreciated, thank you

**Comment by Qengineering** [comment]
It's more an OpenCV or 'pip install' question. 
Usually I remove opencv from the dependency list in the wheel, if possible.

Otherwise, use `$ pip3 install <your package> --no-deps`

You can work with a `requirement.txt` file if other dependencies are needed, but now excluded by the previous --no-deps option. `$ pip3 install -r requirements.txt` 

Below an example of a requirement.txt (PyTorch)
```
# Python dependencies required for development
astunparse
expecttest
future
numpy
psutil
pyyaml
requests
setuptools
six
types-dataclasses
typing_extensions
dataclasses; python_version<"3.7"
```

**Comment by boysugi20** [comment]
Got it

Thank you for your answer
