### ISSUE TITLE
Has anyone been able to get PiCamera (w/ MIDI CSI connection) to work around the 64bit incompatibility?

### ISSUE THREAD

**Issue by Bukkster** [Qengineering/RPi-image#2]
Shell commands like _RASPISTILL_ and _RASPIVID_ are unrecognized and _pip3 install picamera_ fails because pip never finds a compatible version. I think there is a 32bit & 64bit incompatibility with the drivers and the way they use pointers for memory, not exactly sure but that's what I understood from this [thread](https://www.raspberrypi.org/forums/viewtopic.php?t=213435).

Has anyone figured out how I can make the raspberry pi camera work or know any work-arounds for the Qengineering 64bit Pi Image? I'm trying to use video capture for object detection. I've spent hours and days collecting my data, training my models, converting them to the right models and now I can't use the damn camera... fml

**Comment by Qengineering** [comment]
Dear Bukkster,

Sorry to hear about your frustration. However, the solution is very simple.
Whenever you see the line
```
VideoCapture cap("ExampleMovie.mp4");
```
you can replace it with
```
VideoCapture cap(0);
```
Given that you have connected a MIPI PiCamera and in the Preferences->Raspberry Pi Configuration, Tab Interfaces, you have enabled the Camera. OpenCV will now fetches frames from your PiCamera instead of the mp4 movie.

raspistill and raspivid (as programs) are indeed not (yet) supported by the 64-bit OS.

Watch out for '_old_' RaspiForums. 2018 is far too old to give you accurate information on a topic as volatile as an operating system under construction.

**Comment by Bukkster** [comment]
Thanks just checked and yah it works. I actually got one of the ArudCAM motorized cameras with motorized focus, the software they wrote for the the autofocus apps still used standard picamera library, so I got a bit worried when things weren't working.
Cheers

**Comment by im-coder-lg** [comment]
Not trying to reopen, but libcamera is already there on Raspbian 64-bit. I hope it's Bullseye we're taking about.
